### ISSUE TITLE
如何做头部位置推荐？

### ISSUE THREAD

**Issue by Xiangyu33** [bcmi/FOPA-Fast-Object-Placement-Assessment#12]
请教一下作者，原先是采用全身mask和前景去做FOPA，得到的heatmap位置是全身的**中心推荐位置**。
如果想获取头部区域的推荐位置，应该如何做？是如下哪种方式？
1. 只需要把训练标签的pos_label和neg_label换为头部中心
2. 把前景图像和mask和标签全部都换为head区域

**Comment by ustcnewly** [comment]
可以试试把训练标签的pos_label和neg_label换为头部中心。
效果不好的话，可以根据前景图片计算全身中心和头部中心的偏移，对得到的heatmap做整体偏移。
