### ISSUE TITLE
How to generate SOPA encoder by myself?

### ISSUE THREAD

**Issue by DavidXie03** [bcmi/FOPA-Fast-Object-Placement-Assessment#2]
![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/62877238/47d0bff8-1468-42ac-a607-df4823296da2)

**Comment by ustcnewly** [comment]
Refer to "Our SimOPA" in https://github.com/bcmi/Object-Placement-Assessment-Dataset-OPA.
