### ISSUE TITLE
请问config.py中的input_size是如何确定的？

### ISSUE THREAD

**Issue by Nomination-NRB** [bcmi/FOPA-Fast-Object-Placement-Assessment#4]
你好，这个config.py中的input_size是由哪批图片的大小确定的呢，因为我使用原本的input_size=256，在自己的数据集上发生越界：
===========>> 2023-08-17 20:29:50.259114: begin training <<=========== 
Traceback (most recent call last):
  File "train.py", line 283, in <module>
    trainer.train()
  File "train.py", line 131, in train
    mimicking_loss = feature_mimicking(composite_list, feature_pos, feature_map, num, self.dev)
  File "train.py", line 266, in feature_mimicking
    pos_feature[count, :, 0, 0] = feature_map[i, :, int(feature_pos[i, j, 1]), int(feature_pos[i, j, 0])]
IndexError: index 256 is out of bounds for dimension 3 with size 256
(DragGAN) hx@hx:~/FOPA-Fast-Object-Placement-Assessment$

待我修改为input_size=512后则不报此错误，现在由于设备原因，报out of memory，显存不够，虽然还是有问题，但我想知道这个input_size是如何确定的

**Comment by WhynotHAHA** [comment]
您好，在data/all_transforms.py文件中JointResize对输入的图片进行resize，该函数被data.OBdataset.CPDataset中的初始化函数train_triple_transform 调用，CPDataset函数被create_loader调用时self.args["input_size"]作为输入
作为输入标识了resize图片的大小。

您的报错显示在一个维度大小为 256 的数组或张量上，尝试访问了索引为 256 的元素，但在维度 3 上的大小只有 256。您需要检查生成或访问 feature_pos 数组的过程。看起来有一个使用了索引（256）的地方，它超出了给定维度的有效范围。

**Comment by Nomination-NRB** [comment]
> 

非常感谢你的回复，我大概看明白了，所以input_size需要根据使用的数据集来做调整吗
当我使用input_size=256，使用仓库的原始数据，是可以正确训练的
但当我将Input_size设置为128，使用仓库的原始数据，就会报错，和上面提到的错误信息一样
resize图片的大小需要如何限制呢，还是根据经验所设

**Comment by Nomination-NRB** [comment]
> 您好，在data/all_transforms.py文件中JointResize对输入的图片进行resize，该函数被data.OBdataset.CPDataset中的初始化函数train_triple_transform 调用，CPDataset函数被create_loader调用时self.args["input_size"]作为输入 作为输入标识了resize图片的大小。
> 
> 您的报错显示在一个维度大小为 256 的数组或张量上，尝试访问了索引为 256 的元素，但在维度 3 上的大小只有 256。您需要检查生成或访问 feature_pos 数组的过程。看起来有一个使用了索引（256）的地方，它超出了给定维度的有效范围。

非常感谢你的回复，我大概看明白了，所以input_size需要根据使用的数据集来做调整吗
当我使用input_size=256，使用仓库的原始数据，是可以正确训练的
但当我将Input_size设置为128，使用仓库的原始数据，就会报错，和上面提到的错误信息一样
resize图片的大小需要如何限制呢，还是根据经验所设

**Comment by WhynotHAHA** [comment]
<img width="1430" alt="image" src="https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/92723497/9cd9afc8-a51e-47a5-9e78-1529269e38bb">
您好，在将Input_size设置为128并使用仓库的原始数据后并没有出现以上报错信息，能否提供更多相关信息（pos_feature和feature_map）以便查看？

**Comment by Nomination-NRB** [comment]
> <img alt="image" width="1430" src="https://user-images.githubusercontent.com/92723497/263439840-9cd9afc8-a51e-47a5-9e78-1529269e38bb.png"> 您好，在将Input_size设置为128并使用仓库的原始数据后并没有出现以上报错信息，能否提供更多相关信息（pos_feature和feature_map）以便查看？

你好，感谢你的回复！我自己运行的时候结果是这样的：
我使用的数据是这里下载的：
![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/c3321c49-6b3b-4167-84c6-9b9d0a62b71c)

但实际运行就有问题，当input_size=128的时候
![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/bfae4b0e-5293-4c40-9ed1-457f702ccc63)
![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/89706b81-7cfb-407c-91be-70d00db84098)



但是我换回input_size=256就正常运行：
![@QJMUXKH7}L BGDF@J{F895](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/51fe875c-9033-4938-a0e3-c851db72fbed)

**Comment by WhynotHAHA** [comment]
您好，需要对原train.py文件和data/OBdataset.py文件做如下修改：

train.py中：
（1）self.loss = CrossEntropyLoss(ignore_index=127, reduction=self.arg["reduction"]).to(self .dev)中原有的ignore_index由255改为127

data/OBdataset.py中
（1）make_composite函数对所有transforms.Resize((256, 256))中的256改为128
（2）_obtain_target函数中的256改为128（注意：target = np.uint8(np.ones((in_size, in_size)) * (255))保持不变）
（3）CPDataset中__getitem__函数下composite_cat = torch.zeros(50 - len(composite_list), 4, 256, 256)中的256改为128
（4）target_t = self.train_mask_transform(target) * 255 #变成tensor归一化到[0,1]，为了后续计算算回来
        labels_num = (target_t != 255).sum()中的255改为127

<img width="1440" alt="截屏2023-08-28 19 30 22" src="https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/92723497/812565ae-5684-41ea-b992-78587df8b84e">

**Comment by Nomination-NRB** [comment]
> 您好，需要对原train.py文件和data/OBdataset.py文件做如下修改：
> 
> train.py中： （1）self.loss = CrossEntropyLoss(ignore_index=127, reduction=self.arg["reduction"]).to(self .dev)中原有的ignore_index由255改为127
> 
> data/OBdataset.py中 （1）make_composite函数对所有transforms.Resize((256, 256))中的256改为128 （2）_obtain_target函数中的256改为128（注意：target = np.uint8(np.ones((in_size, in_size)) * (255))保持不变） （3）CPDataset中__getitem__函数下composite_cat = torch.zeros(50 - len(composite_list), 4, 256, 256)中的256改为128 （4）target_t = self.train_mask_transform(target) * 255 #变成tensor归一化到[0,1]，为了后续计算算回来 labels_num = (target_t != 255).sum()中的255改为127
> 
> <img alt="截屏2023-08-28 19 30 22" width="1440" src="https://user-images.githubusercontent.com/92723497/263693335-812565ae-5684-41ea-b992-78587df8b84e.png">

你好，我尝试用了你的修改，但还是不能正常训练，配置信息如下：
![USN ALP3W8B@U RZH 50)5O](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/13f2fc9e-ae17-4eeb-b751-7cdc80ced823)
![N_4Z8PKZCQ68J73BXE166MY](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/803814f7-e055-4554-b732-9c1d2ed2db2f)

下方截图依次为 原train.py文件和data/OBdataset.py文件 的修改：
train.py中：
（1）self.loss = CrossEntropyLoss(ignore_index=127, reduction=self.arg["reduction"]).to(self .dev)中原有的ignore_index由255改为127
![619@HEEZUH_POHSVGR83~1O](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/57538f85-5425-4bb5-a44c-7a2345350bf4)


data/OBdataset.py中
（1）make_composite函数对所有transforms.Resize((256, 256))中的256改为128
![FN 9DX7HNR EDI_ 2JCG1BX](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/1c30f0fe-693c-442e-a48f-3c2f422f831c)

（2）_obtain_target函数中的256改为128（注意：target = np.uint8(np.ones((in_size, in_size)) * (255))保持不变）
![V1N1IU5MF4`QG`F4EJFXPS7](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/d5faeaa4-ab90-460a-872d-c34a905b054e)

（3）CPDataset中__getitem__函数下composite_cat = torch.zeros(50 - len(composite_list), 4, 256, 256)中的256改为128
![0){QIQ3%R2NI8LYV~ED(2$K](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/f05f3ec7-dc45-44a0-8264-baeb83067c90)

（4）target_t = self.train_mask_transform(target) * 255 #变成tensor归一化到[0,1]，为了后续计算算回来
labels_num = (target_t != 255).sum()中的255改为127
![4RCGQXJF69BWHXK_EQGKW6N](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/83486284/f53a9bf7-7450-4bb6-9b5b-67162383f693)

**Comment by WhynotHAHA** [comment]
您好，最后一张图片中的target_t = self.train_mask_transform(target) * 255请将255改为127

**Comment by Nomination-NRB** [comment]
> 您好，最后一张图片中的target_t = self.train_mask_transform(target) * 255请将255改为127

非常感谢你！现在可以正确训练了，256和128都可以正常训练了

可以问一下为什么这些调整是“额外的”吗？因为原仓库里面不做这些调整的话无法修改input_size的值

train.py中：
（1）self.loss = CrossEntropyLoss(ignore_index=127, reduction=self.arg["reduction"]).to(self .dev)中原有的ignore_index由255改为127

data/OBdataset.py中
（1）make_composite函数对所有transforms.Resize((256, 256))中的256改为128
（2）_obtain_target函数中的256改为128（注意：target = np.uint8(np.ones((in_size, in_size)) * (255))保持不变）
（3）CPDataset中__getitem__函数下composite_cat = torch.zeros(50 - len(composite_list), 4, 256, 256)中的256改为128
（4）target_t = self.train_mask_transform(target) * 255 #变成tensor归一化到[0,1]，为了后续计算算回来
labels_num = (target_t != 255).sum()中的255改为127

**Comment by WhynotHAHA** [comment]
用于训练的bg原有的图片宽高各异，将其resize到256*256大小，相应的原有的label位置随之调整；为了方便调整您可以在以上位置新添加input_size变量统一修改

**Comment by Nomination-NRB** [comment]
> 用于训练的bg原有的图片宽高各异，将其resize到256*256大小，相应的原有的label位置随之调整；为了方便调整您可以在以上位置新添加input_size变量统一修改

那为什么我做了以上设置后，input_size=128和256都可以正常训练，按道理来说我不应该将以上修改撤回才可能训练256的size吗

**Comment by WhynotHAHA** [comment]
您好，虽然在128设置下input_size设置为256能够跑起来，但是代码内部发生了错误，比如此时resize后的标签位置已经发生了错误，只是因为多维列表索引值可以为负数而没有报错：

<img width="224" alt="截屏2023-08-30 14 58 59" src="https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/92723497/ad786230-4f4d-4c4d-b238-fda3cec088f3">
<img width="244" alt="截屏2023-08-30 14 59 19" src="https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/92723497/a3eae8d1-5bd8-41bc-ae77-5b675b942584">

**Comment by Nomination-NRB** [comment]
> 您好，虽然在128设置下input_size设置为256能够跑起来，但是代码内部发生了错误，比如此时resize后的标签位置已经发生了错误，只是因为多维列表索引值可以为负数而没有报错：
> 
> <img alt="截屏2023-08-30 14 58 59" width="224" src="https://user-images.githubusercontent.com/92723497/264258448-ad786230-4f4d-4c4d-b238-fda3cec088f3.png"> <img alt="截屏2023-08-30 14 59 19" width="244" src="https://user-images.githubusercontent.com/92723497/264258519-a3eae8d1-5bd8-41bc-ae77-5b675b942584.png">

哦哦，非常感谢你的解释！所以这个input_size需要根据我们输入图片的尺寸来确定，然后为了方便调整，在以上位置新添加input_size变量统一修改，我可以这样理解吗

**Comment by WhynotHAHA** [comment]
可以这么理解

**Comment by Nomination-NRB** [comment]
> 可以这么理解

okk

**Comment by Xiangyu33** [comment]
我在训练自己数据的时候，也遇到了这个问题。
不过是训练了很多iter之后发生的报错IndexError: index 256 is out of bounds for dimension 3 with size 256

我没有改input_size  256的尺寸，可能我的数据存在尺寸问题。。

**Comment by WhynotHAHA** [comment]
你在试图访问一个数组或张量的第 256 索引，但该数组或张量的第 3 维的大小为 256，而 Python 中索引是从 0 开始的，因此有效索引范围是 0 到 255（包含 255），256 超出了可访问的范围。请仔细检查自己构建的数据的label坐标在resize前后的变化。
