### ISSUE TITLE
Do you plan to provide link of datasets other than Baidu Cloud, such as Google Drive or OneDrive?

### ISSUE THREAD

**Issue by DJLee68** [bcmi/FOPA-Fast-Object-Placement-Assessment#5]
Do you plan to provide link of datasets other than Baidu Cloud, such as Google Drive or OneDrive?

**Comment by ustcnewly** [comment]
Yes, we will add the google drive link.

**Comment by DJLee68** [comment]
Thanks!

**Comment by ustcnewly** [comment]
We have added the google drive link.
