### ISSUE TITLE
About differences with OPA sets

### ISSUE THREAD

**Issue by DJLee68** [bcmi/FOPA-Fast-Object-Placement-Assessment#6]
Thanks to you sharing the Google Drive link to the FOPA dataset, I was able to download and check the dataset successfully. However, while checking the dataset, I noticed that the labeling is different from the original OPA dataset.

![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/41410971/4a8ef997-94cf-43cb-a3ff-851bce340615)
(FOPA labeling)

![image](https://github.com/bcmi/FOPA-Fast-Object-Placement-Assessment/assets/41410971/b9375a5d-2ffb-4769-8266-95672d37002d)
(OPA labeling)

As you can see in this sample with the same bg, fg, and scale, the position values in the OPA set are different from the position values in the FOPA set. How can I interpret this? As far as I know, the labels that existed at image-level in the OPAset have been moved to pixel-level, so why are the position values different?

**Comment by WhynotHAHA** [comment]
For [x,y,w,h] in the opa dataset, the conversion to the FOPA dataset is x'=x+0.5*w, y'=h+0.5*h. That is, x and y in the OPA data set represent the coordinates of the upper left corner of the bounding box of the foreground object, while x' and y' in the FOPA data set represent the coordinates of the center point of the bounding box.

**Comment by DJLee68** [comment]
got it. thank u so much !!
