### ISSUE TITLE
请问下，你们有相关TERSE的源码

### ISSUE THREAD

**Issue by 1cai2** [bcmi/FOPA-Fast-Object-Placement-Assessment#8]
我阅读了你们的文章，对我很有启示。里面提到TERSE模型，你们用自己的OPA数据集进行训练然后判断其位置合理性。但当我找到TERSE原文时，却没发现源码。如果可以的话能否把这个源码链接发给我呢？我的qq邮箱为2371247291@qq.com

**Comment by ustcnewly** [comment]
我们的GracoNet仓库里有baselines的代码 https://github.com/bcmi/GracoNet-Object-Placement
