### ISSUE TITLE
只有positive label，neg为空，训练出的heatmap几乎全白。

### ISSUE THREAD

**Issue by Xiangyu33** [bcmi/FOPA-Fast-Object-Placement-Assessment#9]
仿照原始的训练数据格式，整理了自己的训练数据。数据格式基本如下，只有pos_label,neg_label为空：
![image](https://github.com/user-attachments/assets/e1b7faa2-80b3-40cb-a470-4f5518467418)

训练过程loss正常收敛

这样训练后的推理图像，每个heatmap都几乎为全白
![image](https://github.com/user-attachments/assets/aacb9f1d-9047-48ca-a3f9-d845c542ea8a)
与原始作者训练结果有较大差距，如下：
![image](https://github.com/user-attachments/assets/e12610a4-cbcb-4a27-be34-da0b5b939929)

请问只有pos_label的训练，只有全白heatmap是否符合预期

**Comment by WhynotHAHA** [comment]
只有pos_label的训练，只会输出全白heatmap，因为只要全都预测为positive就符合训练集需求

**Comment by Xiangyu33** [comment]
我试试其他加入neg的方式（随机高斯点、边界点、其他检测物的坐标），效果不好我再找人工试试
